# fly.toml file generated for fullstackpart11 on 2023-05-18T14:14:22+03:00

app = "fullstackpart11"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[deploy]
  release_command = "npm run build"

[processes]
  app = "node app.js"

[build]
  builder = "heroku/buildpacks:20"
  [build.args]
    NODE_VERSION = "16.9.0"

[env]
  PORT = "8080"

[experimental]
  auto_rollback = true

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [services.checks]
    [[services.tcp_checks]]
      grace_period = "1s"
      interval = "15s"
      restart_limit = 0
      timeout = "2s"
    
    [[services.script_checks]]
      command = "./health_check.sh"
      grace_period = "1s"
      interval = "5s"
      restart_limit = 0
      timeout = "1s"